import { FormEvent, useEffect, useState } from "react";
import { motion } from "framer-motion";

type Project = { slug: string; name: string; category: "Residential" | "Commercial"; location: string; area: string; year: string; image: string; description: string };

const projects: Project[] = [
  { slug: "courtyard-residence", name: "The Courtyard Residence", category: "Residential", location: "Erode, Tamil Nadu", area: "2,650 sq. ft.", year: "2024", image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1500&q=85", description: "A bright, contemporary family home shaped around a private courtyard and practical everyday living." },
  { slug: "urban-business-centre", name: "Urban Business Centre", category: "Commercial", location: "Erode, Tamil Nadu", area: "8,400 sq. ft.", year: "2023", image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1500&q=85", description: "A considered commercial space with a durable exterior, efficient floor plates, and a crisp professional finish." },
  { slug: "garden-villa", name: "Garden Villa", category: "Residential", location: "Perundurai, Tamil Nadu", area: "3,120 sq. ft.", year: "2024", image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1500&q=85", description: "A calm, modern villa where natural light, garden views, and material quality lead the design." }
];

const services = [
  ["01", "Building Construction", "Reliable residential and commercial construction from foundation to handover."],
  ["02", "Plan Approval", "Guidance and coordination to move your project forward with clarity."],
  ["03", "Elevation & Model Plan", "Thoughtful elevations and plans that bring your ideas into clear view."],
  ["04", "Estimation", "Detailed, practical cost estimates to support informed decisions."],
  ["05", "DTCP Approval", "Support for approval requirements and the related documentation process."],
  ["06", "Housing Loan Support", "Helpful assistance as you navigate your home-financing process."]
];

const phone = "9688983076";
const wa = `https://wa.me/91${phone}`;
const contact = { email: "jsrealpromoters1@gmail.com", address: "145, Ganapathy Building, 2nd Floor, Near Railway Station, Erode – 638 001", gstin: "33AARFJ4614N1ZY" };

function Logo() {
  return <a className="brand" href="/" onClick={(e) => navigate(e, "/")} aria-label="JS Real Promoters home"><svg viewBox="0 0 52 52" aria-hidden="true"><circle cx="26" cy="26" r="23" fill="none" stroke="currentColor" strokeWidth="4"/><path d="M14 36V24l7-8v20m3 0V11l7 7v18m3 0V21l5 5v10" fill="none" stroke="currentColor" strokeWidth="3" strokeLinejoin="round"/></svg><span><b>JS REAL</b><small>PROMOTERS</small></span></a>;
}

function navigate(event: React.MouseEvent<HTMLAnchorElement>, to: string) { event.preventDefault(); window.history.pushState({}, "", to); window.dispatchEvent(new PopStateEvent("popstate")); window.scrollTo({ top: 0, behavior: "smooth" }); }
function Link({ to, children, className = "" }: {to: string; children: React.ReactNode; className?: string}) { return <a href={to} className={className} onClick={(e) => navigate(e, to)}>{children}</a>; }

function Header() {
  const [open, setOpen] = useState(false);
  return <header><div className="nav shell"><Logo/><button className="menu" onClick={() => setOpen(!open)} aria-label="Toggle menu">{open ? "×" : "☰"}</button><nav className={open ? "open" : ""}><Link to="/services">Services</Link><Link to="/projects">Projects</Link><Link to="/about">About us</Link><Link to="/contact">Contact</Link><Link to="/contact" className="button button-small">Get a quote</Link></nav></div></header>;
}
function Footer() { return <footer><div className="shell footer-grid"><div><Logo/><p>Building spaces with care, clarity, and a commitment to quality.</p></div><div><h4>Explore</h4><Link to="/services">Services</Link><Link to="/projects">Projects</Link><Link to="/about">About us</Link></div><div><h4>Contact</h4><a href={`tel:+91${phone}`}>+91 96889 83076</a><a href={`mailto:${contact.email}`}>{contact.email}</a><p>{contact.address}</p></div></div><div className="shell footer-bottom"><span>© {new Date().getFullYear()} JS Real Promoters</span><span>GSTIN: {contact.gstin}</span></div></footer>; }
function SectionTitle({ eyebrow, title, copy }: {eyebrow: string; title: string; copy?: string}) { return <div className="section-intro"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2>{copy && <p>{copy}</p>}</div>; }

function Home() { return <>
  <section className="hero"><div className="hero-image"/><div className="hero-overlay"/><div className="shell hero-content"><motion.p initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} transition={{duration:.55}} className="eyebrow light">Erode · Tamil Nadu</motion.p><motion.h1 initial={{opacity:0,y:22}} animate={{opacity:1,y:0}} transition={{duration:.65, delay:.08}}>Building quality.<br/><em>Creating trust.</em></motion.h1><motion.p initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} transition={{duration:.65, delay:.16}} className="hero-copy">Engineer-led construction, planning, approvals, and estimates for the spaces that matter to your family and future.</motion.p><motion.div initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} transition={{duration:.65, delay:.24}} className="actions"><Link to="/projects" className="button">View projects <i>→</i></Link><Link to="/contact" className="button button-ghost">Free consultation</Link></motion.div></div></section>
  <section className="proof"><div className="shell proof-grid"><div><span>Engineer-led</span><b>Planning & construction</b></div><div><span>Local expertise</span><b>Erode & surrounding areas</b></div><div><span>Clear support</span><b>From plan to handover</b></div><div><span>Registered business</span><b>GSTIN verified details</b></div></div></section>
  <section className="section shell"><SectionTitle eyebrow="WHAT WE DO" title="A clear path from idea to built space." copy="Every project begins with listening. We combine practical planning, careful coordination, and a quality-first approach to make the process feel more certain."/><div className="service-grid">{services.map(([number, title, text]) => <Link to="/services" className="service-card" key={title}><span>{number}</span><h3>{title}</h3><p>{text}</p><i>↗</i></Link>)}</div></section>
  <section className="section project-feature"><div className="shell"><SectionTitle eyebrow="SELECTED WORK" title="Spaces made for real life."/><div className="featured-projects">{projects.slice(0,2).map(p => <ProjectCard key={p.slug} project={p}/>)}</div><Link to="/projects" className="text-link">See all projects <i>→</i></Link></div></section>
  <section className="section shell split"><div className="split-image"/><div className="split-content"><SectionTitle eyebrow="WHY JS REAL PROMOTERS" title="Professional guidance at every stage."/><ul className="tick-list"><li>Engineer-led project thinking</li><li>Practical estimates and clear process</li><li>Support for plans and approvals</li><li>Quality-focused construction execution</li><li>Direct, local communication</li></ul><Link to="/about" className="text-link">Learn about us <i>→</i></Link></div></section>
  <section className="section process"><div className="shell"><SectionTitle eyebrow="OUR PROCESS" title="Built around clarity."/><div className="steps">{["Consult", "Plan", "Design", "Estimate", "Construct", "Inspect", "Handover"].map((x,i) => <div key={x}><b>0{i+1}</b><span>{x}</span></div>)}</div></div></section>
  <CTA/></> }

function ProjectCard({ project }: {project: Project}) { return <Link to={`/projects/${project.slug}`} className="project-card"><div className="project-image" style={{backgroundImage:`url(${project.image})`}}/><div className="project-meta"><span>{project.category} · {project.year}</span><h3>{project.name}</h3><p>{project.location}</p></div></Link>; }
function Services() { return <><PageHero eyebrow="SERVICES" title="Practical expertise for every stage." copy="From the first plan to final handover, we help bring clarity to the work ahead."/><section className="section shell"><div className="service-grid service-full">{services.map(([number,title,text]) => <article className="service-card" key={title}><span>{number}</span><h3>{title}</h3><p>{text}</p><i>↗</i></article>)}</div></section><CTA/></> }
function Projects() { const [filter,setFilter] = useState("All"); const shown = filter === "All" ? projects : projects.filter(x => x.category === filter); return <><PageHero eyebrow="OUR WORK" title="A portfolio built with care." copy="A selection of residential and commercial spaces shaped around their owners’ needs."/><section className="section shell"><div className="filters">{["All","Residential","Commercial"].map(x=><button className={filter===x?"active":""} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div><div className="project-grid">{shown.map(p=><ProjectCard project={p} key={p.slug}/>)}</div></section><CTA/></> }
function ProjectDetail({ project }: {project: Project}) { return <><section className="detail-hero" style={{backgroundImage:`linear-gradient(90deg,rgba(22,27,28,.68),rgba(22,27,28,.12)),url(${project.image})`}}><div className="shell"><span className="eyebrow light">{project.category} · {project.location}</span><h1>{project.name}</h1><p>{project.description}</p></div></section><section className="section shell facts"><SectionTitle eyebrow="PROJECT OVERVIEW" title="Designed for enduring value."/><div><b>{project.area}</b><span>Built-up area</span></div><div><b>{project.year}</b><span>Completion year</span></div><div><b>{project.category}</b><span>Project type</span></div></section><section className="section shell split"><div className="split-content"><SectionTitle eyebrow="THE APPROACH" title="Quality in the details." copy="Each stage is coordinated with the project’s practical needs in mind—from material choices and workmanship to a clean, considered final handover."/><Link to="/contact" className="button dark">Discuss a similar project <i>→</i></Link></div><div className="detail-image" style={{backgroundImage:`url(${project.image})`}}/></section><CTA/></> }
function About() { return <><PageHero eyebrow="ABOUT US" title="Local knowledge. Personal commitment." copy="JS Real Promoters brings together planning, approvals, design support, and construction under one practical, client-focused team."/><section className="section shell split"><div className="about-image"/><div className="split-content"><SectionTitle eyebrow="OUR APPROACH" title="A more confident way to build."/><p>We believe a project should feel understandable from the first conversation. That means listening carefully, communicating directly, and helping clients make considered decisions at each stage.</p><p>Based in Erode, we support families and businesses with the expertise needed to turn a site, plan, or ambition into a well-executed space.</p></div></section><section className="section team"><div className="shell"><SectionTitle eyebrow="THE TEAM" title="Direct expertise, close to the work."/><div className="team-grid"><article><span>ER.</span><h3>Shankar K</h3><p>Construction & project guidance</p><a href="tel:+919688983076">+91 96889 83076</a></article><article><span>ER.</span><h3>Aswanth Raj K, B.E.</h3><p>Planning & project guidance</p><a href="tel:+917010195727">+91 70101 95727</a></article></div></div></section><CTA/></> }
function Contact() {
  const [sent, setSent] = useState(false);
  const [sending, setSending] = useState(false);
  const [error, setError] = useState("");
  const [whatsappText, setWhatsappText] = useState("Hello JS Real Promoters, I would like to discuss my construction project.");
  async function submit(e: FormEvent<HTMLFormElement>) {
    e.preventDefault(); const values = new FormData(e.currentTarget);
    setWhatsappText(`Hello JS Real Promoters, I am ${values.get("name")} and would like to discuss a ${values.get("service")} project in ${values.get("location")}. Budget: ${values.get("budget")}. Timeline: ${values.get("timeline")}.`);
    setSending(true); setError("");
    try { const endpoint = import.meta.env.VITE_FORMSPREE_ENDPOINT as string | undefined; if (endpoint) { const response = await fetch(endpoint, { method: "POST", headers: { Accept: "application/json" }, body: values }); if (!response.ok) throw new Error("We could not send your enquiry. Please use WhatsApp or call us directly."); } setSent(true); }
    catch (err) { setError(err instanceof Error ? err.message : "Unable to send your enquiry right now."); }
    finally { setSending(false); }
  }
  return <><PageHero eyebrow="CONTACT" title="Tell us what you want to build." copy="Share a few details and we’ll help you take the next clear step."/><section className="section shell contact-layout"><div><SectionTitle eyebrow="VISIT OR CALL" title="Let’s start a conversation."/><div className="contact-list"><p><b>Office</b>{contact.address}</p><p><b>Email</b><a href={`mailto:${contact.email}`}>{contact.email}</a></p><p><b>Er. Shankar K</b><a href="tel:+919688983076">+91 96889 83076</a></p><p><b>Er. Aswanth Raj K, B.E.</b><a href="tel:+917010195727">+91 70101 95727</a></p><p><b>GSTIN</b>{contact.gstin}</p></div></div><div className="form-wrap">{sent ? <div className="form-success"><span>✓</span><h2>Thank you.</h2><p>Your enquiry is ready. Continue on WhatsApp to speak with Er. Shankar K.</p><a className="button dark" href={`${wa}?text=${encodeURIComponent(whatsappText)}`} target="_blank" rel="noreferrer">Continue on WhatsApp <i>→</i></a></div> : <form onSubmit={submit}><h2>Request a consultation</h2><div className="form-row"><label>Name<input required name="name" placeholder="Your full name"/></label><label>Phone<input required name="phone" type="tel" placeholder="Your phone number"/></label></div><label>Email<input required name="email" type="email" placeholder="you@example.com"/></label><div className="form-row"><label>Project type<select name="service"><option>Building Construction</option><option>Plan Approval</option><option>Elevation / Model Plan</option><option>Estimation</option><option>DTCP Approval</option><option>Housing Loan Support</option></select></label><label>Location<input required name="location" placeholder="Project location"/></label></div><div className="form-row"><label>Estimated budget<select name="budget"><option>Not decided yet</option><option>Under ₹25 lakh</option><option>₹25–50 lakh</option><option>₹50 lakh–1 crore</option><option>Above ₹1 crore</option></select></label><label>Timeline<select name="timeline"><option>Planning now</option><option>Within 3 months</option><option>3–6 months</option><option>More than 6 months</option></select></label></div><label>Tell us about your project<textarea name="message" rows={4} placeholder="Land size, requirements, or any questions..."/></label>{error && <p className="form-error">{error}</p>}<button className="button dark" type="submit" disabled={sending}>{sending ? "Sending…" : "Send enquiry"} <i>→</i></button></form>}</div></section></> }
function PageHero({ eyebrow,title,copy }: {eyebrow:string;title:string;copy:string}) { return <section className="page-hero"><div className="shell"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{copy}</p></div></section>; }
function CTA() { return <section className="cta"><div className="shell"><span className="eyebrow light">START A CONVERSATION</span><h2>Let’s build your next chapter.</h2><p>Talk to our team about your site, plan, or project idea.</p><Link to="/contact" className="button">Book a consultation <i>→</i></Link></div></section>; }

function App() { const [path,setPath] = useState(window.location.pathname); useEffect(()=>{ const handler=()=>setPath(window.location.pathname); addEventListener("popstate",handler); return()=>removeEventListener("popstate",handler); },[]); let page: React.ReactNode; const project = projects.find(x=>`/projects/${x.slug}`===path); if(project) page=<ProjectDetail project={project}/>; else if(path==="/") page=<Home/>; else if(path==="/services") page=<Services/>; else if(path==="/projects") page=<Projects/>; else if(path==="/about") page=<About/>; else if(path==="/contact") page=<Contact/>; else page=<><PageHero eyebrow="404" title="Page not found." copy="The page you are looking for is not available."/><div className="shell section"><Link to="/" className="button dark">Back home</Link></div></>; return <><Header/><main>{page}</main><Footer/><a className="whatsapp" href={wa} target="_blank" rel="noreferrer" aria-label="Chat on WhatsApp">◔</a></>; }
export default App;
